version: '3'
services:
  nodejs-server:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    container_name: node-api
    volumes:
       - ./Server:/usr/src/api
       - /usr/src/api/node_modules
  react-ui:
    build:
      context: ./Server/client
    ports:
      - "3080:3080"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./Server/client:/usr/src/app
       - /usr/src/app/node_modules